# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Simulate CircuitPython'
description: 'Simulate CircuitPython using Zephyr simulator'
inputs:
  version:
    description: 'Version of CircuitPython to simulate'
    required: true
    default: main
  circuitpy:
    description: 'Filepath to file or folder of files to add to the simualted CIRCUITPY'
    required: true
  circuitpython-folder:
    description: 'Folder name to use for the CircuitPython checkout'
    required: true
    default: 'cpysim'
outputs:
  output-text:
    description: 'The text output from the simulator'
    value: ${{ steps.run-sim.outputs.simout }}
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12
    - name: Checkout CircuitPython repository
      uses: actions/checkout@v6
      with:
        repository: adafruit/circuitpython
        path: ${{ inputs.circuitpython-folder }}
        ref: ${{ inputs.version }}
        fetch-depth: 0
    - name: Determine cache key
      id: cache-key
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}
      run: |
        if [[ "${{ inputs.version }}" == "main" ]]; then
          GITREV=$(git rev-parse --short HEAD)
          CACHE_KEY="$GITREV-zephyr-cache"
        else
          CACHE_KEY="${{ inputs.version }}-zephyr-cache"
        fi
        echo "CACHE_KEY=$CACHE_KEY" >> $GITHUB_OUTPUT
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libusb-1.0-0-dev \
          libudev-dev \
          mtools \
          protobuf-compiler \
          dosfstools \
          gcc-multilib \
          g++-multilib
    - name: Cache firmware build
      id: cache-firmware
      uses: actions/cache@v5
      with:
        path: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp/build-native_native_sim/firmware.exe
        key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    - name: Fetch submodules
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: make fetch-port-submodules
    - name: Install CircuitPython dev dependencies
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: pip install -r requirements-dev.txt
    - name: Install west
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: pip install west
    - name: Create west workspace
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: west init -l zephyr-config
    - name: Update west project
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: west update
    - name: Export Zephyr installation
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: west zephyr-export
    - name: Install Zephyr script dependencies
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: |
        pip install -r zephyr/scripts/requirements.txt
        pip install protobuf grpcio-tools
    - name: Install Zephyr SDK
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: west sdk install
    - name: Make the firmware
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      if: steps.cache-firmware.outputs.cache-hit != 'true'
      run: make BOARD=native_native_sim BUILD=build-native_native_sim build-native_native_sim/firmware.exe
    - name: Create flash space
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      run: |
        truncate -s 2M build-native_native_sim/flash.bin
        mformat -i build-native_native_sim/flash.bin ::
    - name: Create CIRCUITPY folder
      shell: bash
      run: |
        python ${{ github.action_path }}/scripts/prepare.py ${{ inputs.circuitpy }} ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
    - name: Add files to flash
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      run: mcopy -s -i build-native_native_sim/flash.bin CIRCUITPY/* ::;
    - name: Run simulator script
      id: run-sim
      shell: bash
      working-directory: ${{ inputs.circuitpython-folder }}/ports/zephyr-cp
      run: |
        SIM_OUTPUT=$(python ${{ github.action_path }}/scripts/simulate.py)
        {
          echo "simout<<EOF"
          echo "$SIM_OUTPUT"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
