# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Prepare system'
description: 'Prepare the system for building/running the simulator'
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libusb-1.0-0-dev \
          libudev-dev \
          mtools \
          protobuf-compiler \
          dosfstools \
          gcc-multilib \
          g++-multilib \
          libsdl2-dev
