# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Simulate CircuitPython'
description: 'Simulate CircuitPython using Zephyr simulator'
inputs:
  firmware-filepath:
    description: 'Filepath to firmware executable file'
    required: true
    default: './firmware.exe'
  flash-filepath:
    description: 'Filepath to flash binary file'
    required: true
    default: './flash.bin'
outputs:
  output-text:
    description: 'The text output from the simulator'
    value: ${{ steps.run-sim.outputs.simout }}
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libusb-1.0-0-dev \
          libudev-dev \
          mtools \
          protobuf-compiler \
          dosfstools \
          gcc-multilib \
          g++-multilib
    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install simulator command
      shell: bash
      run: pipx install ${{ github.action_path }}/..
    - name: Run simulator script
      id: run-sim
      shell: bash
      run: |
        SIM_OUTPUT=$(simulate-circuitpython ${{ inputs.firmware-filepath }} ${{ inputs.flash-filepath }})
        {
          echo "simout<<EOF"
          echo "$SIM_OUTPUT"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
    - name: Uninstall simulator script
      shell: bash
      run: pipx uninstall simulate-circuitpython-nativesim
