# SPDX-FileCopyrightText: 2026 Alec Delaney
# SPDX-License-Identifier: MIT

name: 'Simulate CircuitPython'
description: 'Simulate CircuitPython using Zephyr simulator'
inputs:
  flash-filepath:
    description: 'Filepath for the desired flash binary file'
    required: true
    default: './flash.bin'
  circuitpy:
    description: 'Filepath to file or folder of files to add to the simualted CIRCUITPY'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libusb-1.0-0-dev \
          libudev-dev \
          mtools \
          protobuf-compiler \
          dosfstools \
          gcc-multilib \
          g++-multilib
    - name: Install flash preparation command
      shell: bash
      run: pipx install ${{ github.action_path }}/..
    - name: Create flash space
      shell: bash
      run: prepare-flash ${{ inputs.flash-filepath }} ${{ inputs.circuitpy }}
    - name: Uninstall flash preparation command
      shell: bash
      run: pipx uninstall simulate-circuitpython-nativesim
